{% set name = "vt-py" %}
{% set version = "0.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 32e85a835e79b6ddf60165f71292e98fe6c078b5c960ca4c4335e692d7856c09

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
  run:
    - aiofiles
    - aiohttp ==3.8.6
    - python >={{ python_min }}

test:
  imports:
    - vt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.virustotal.com/gui/
  summary: The official Python client library for VirusTotal
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://virustotal.github.io/vt-py/
  doc_url: https://github.com/VirusTotal/vt-py

extra:
  recipe-maintainers:
    - BastianZim
