{% set name = "vt-py" %}
{% set version = "0.20.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f0260036e4f483471776dece6275373d98288435c839b562ba47902399eca1cc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
  run:
    - aiofiles
    - aiohttp ==3.8.6
    - python >={{ python_min }}

test:
  imports:
    - vt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.virustotal.com/gui/
  summary: The official Python client library for VirusTotal
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://virustotal.github.io/vt-py/
  doc_url: https://github.com/VirusTotal/vt-py

extra:
  recipe-maintainers:
    - BastianZim
