{% set name = "vt-py" %}
{% set version = "0.18.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e7a8812b0e5bf25b4808f5f1aacc3949dafe2affad6774e1885d45a459c22e80

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - aiohttp ==3.8.6
    - python >=3.6

test:
  imports:
    - vt
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.virustotal.com/gui/
  summary: The official Python client library for VirusTotal
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://virustotal.github.io/vt-py/
  doc_url: https://github.com/VirusTotal/vt-py

extra:
  recipe-maintainers:
    - BastianZim
